// =======================================================
// Generated by alifecontest-java application.
//   @author Sergio Del Castillo
//   @e-mail:sergiodelcastillo@ymail.com
// =======================================================

#ifndef MOVENEVER_H
#define MOVENEVER_H

#include<cstdlib>
#include<ctime>
#include <iostream>
using namespace std;

#include "Microorganism.h"

class MoveNever: public Microorganism{
	public:
		MoveNever(){
		}
		void move(Movement &mov) {
		};

		bool mitosis(){
			return false;
		};

		string getName(){
			return "MoveNever_cpp";
		};

		string getAuthor(){
			return "Judge";
		};

		string getAffiliation(){
			return "Judge";
		};
};

#endif


