// =======================================================
// Generated by alifecontest-java application.
//   @author Sergio
//   @e-mail:sergiodelcastillo@ymail.com
// =======================================================

package MOs;

import MOs.Tactica2Lib.Tactica2Lib;
import controller.java.Microorganism;
import controller.java.Movement;
import controller.java.Petri;
import controller.java.Position;
import data.java.Defs;

public class Tactica2 extends Microorganism{
    Tactica2Lib p;

    public void move(Movement mov) {

        p = new Tactica2Lib(0,0);
        for(int i = -1; i <= 1; i++){
           for(int j = -1; j <= 1; j++){
              try{
                  p.x = pos.x+i;
                  p.y = pos.y+j;
                 if(Petri.getInstance().inDish(new Position(p.x,p.y)) &&
                    Petri.getInstance().canCompete(pos, new Position(p.x, p.y))){
                     if(Petri.getInstance().getEnergy(p.x, p.y) < ene-Defs.LESS_MOVE){
                        mov.dx = i;
                        mov.dy = j;
                        return;
                     }
                 }
              } catch(NullPointerException ignored){ }
           }
       }
       for(int i = -1; i <= 1; i++){
         for(int j = -1; j <= 1; j++){
           try{
               p.x = pos.x+i;
               p.y = pos.y+j;
               if(Petri.getInstance().inDish(p.x, p.y)){
                  // I like 1.4  --> you can change it!
                 if(Petri.getInstance().getNutrient(pos.x, pos.y)*1.4 <
                    Petri.getInstance().getNutrient(p.x,p.y)){  
                     mov.dx = i;
                      mov.dy = j;
                      return;
                   }
                 }
              } catch(NullPointerException ignored){}
           }
       }
    }

    public boolean mitosis() {
      return false;
    }

    public String getName() {
        return "Tactica2_java";
    }

    public String getAuthor() {
        return "Tactica2";
    }

	  public String getAffiliation() {
		   return "UTN-FRSF";
	  }
}

