// =======================================================
// Generated by alifecontest-java application.
//   @author Sergio Del Castillo
//   @e-mail:sergiodelcastillo@ymail.com
// =======================================================

#ifndef MOVX_H
#define MOVX_H

#include<cstdlib>
#include <iostream>
using namespace std;

#include "Microorganism.h"
#include "Petri.h"

class Movx: public Microorganism{
	public:
		Movx(){
//			srand(time(NULL));
		}
		void move(Movement &mov) {
			mov.dx = (rand() % 3) -1;
			mov.dy = 0;
		};

		bool mitosis(){
			return false;
		};

		string getName(){
			return "Movx_cpp";
		};

		string getAuthor(){
			return "Author";
		};

		string getAffiliation(){
			return "UTN-FRSF";
		};
};

#endif


