// =======================================================
// Generated by alifecontest-java application.
//   @author Sergio
//   @e-mail:sergiodelcastillo@ymail.com
// =======================================================

package MOs;


import alifec.core.simulation.Defs;
import alifec.core.simulation.Microorganism;
import alifec.core.simulation.Movement;
import alifec.core.simulation.Position;
import alifec.core.simulation.Petri;

public class Tactica2 extends Microorganism {

    public void move(Movement mov) {
        int px = 0;
        int py = 0;
        for (int i = -1; i <= 1; i++) {
            for (int j = -1; j <= 1; j++) {
                try {
                    px = x + i;
                    py = y + j;
                    if (Petri.getInstance().inDish(px, py) &&
                            Petri.getInstance().canCompete(x, y, px, py)) {
                        if (Petri.getInstance().getEnergy(px, py) < ene - Defs.LESS_MOVE) {
                            mov.dx = i;
                            mov.dy = j;
                            return;
                        }
                    }
                } catch (NullPointerException ex) {
                }
            }
        }
        for (int i = -1; i <= 1; i++) {
            for (int j = -1; j <= 1; j++) {
                try {
                    px = x + i;
                    py = y + j;
                    if (Petri.getInstance().inDish(px, py)) {
                        // I like 1.4  --> you can change it!
                        if (Petri.getInstance().getNutrient(x, y) * 1.4 <
                                Petri.getInstance().getNutrient(px, py)) {
                            mov.dx = i;
                            mov.dy = j;
                            return;
                        }
                    }
                } catch (NullPointerException ex) {
                }
            }
        }
    }

    public boolean mitosis() {
        return false;
    }

    public String getName() {
        return "Tactica2_java";
    }

    public String getAuthor() {
        return "Tactica2";
    }

    public String getAffiliation() {
        return "UTN-FRSF";
    }
}

