// =======================================================
// Generated by alifecontest-java application.
//   @author Sergio Del Castillo
//   @e-mail:sergiodelcastillo@ymail.com
// =======================================================
package MOs;

import alifec.core.simulation.*;


import alifec.core.simulation.Microorganism;
import alifec.core.simulation.Movement;
import alifec.core.simulation.Position;


public class Tactica1 extends Microorganism {
    Petri petri = Petri.getInstance();

    public void move(Movement mov) {
        mov.dx = mov.dy = 0;

        //if I can attack you --> I kill you :o
        for (int i = -1; i <= 1; i++) {
            for (int j = -1; j <= 1; j++) {
                Position p = new Position(x + i, y + j);

                if (petri.inDish(p) &&
                        petri.canCompete(x, y, p.x, p.y) &&
                        ene > petri.getEnergy(p.x, p.y)) {
                    mov.dx = i;
                    mov.dy = j;
                    return;
                }
            }
        }
        // if I can't attack -->   Seek the maximun of Relative Nutrient!!
        for (int i = -1; i <= 1; i++) {
            for (int j = -1; j <= 1; j++) {
                Position current = new Position(x + i, y + j);
                Position best = new Position(x + mov.dx, y + mov.dy);

                if (petri.inDish(current) &&
                        petri.getNutrient(best.x, best.y) < petri.getNutrient(current.x, current.y)) {
                    mov.dx = i;
                    mov.dy = j;
                }
            }
        }
    }

    public boolean mitosis() {
        return (this.ene > Defs.E_INITIAL * 2);
    }

    public String getName() {
        return "Tactica1_java";
    }

    public String getAuthor() {
        return "Tactica1";
    }

    public String getAffiliation() {
        return "UTN-FRSF";
    }
}

