// =======================================================
// Generated by alifecontest-java application.
//   @author Sergio Del Castillo
//   @e-mail:sergiodelcastillo@ymail.com
// =======================================================

package MOs;


import controller.java.Microorganism;
import controller.java.Movement;

public class MitosisTrue extends Microorganism {
    public void move(Movement mov) {
    }

    public boolean mitosis() {
        return true;
    }

    public String getName() {
        return "MitosisTrue_java";
    }

    public String getAuthor() {
        return "Judge";
    }

    public String getAffiliation() {
        return "Judge";
    }
}

